// <auto-generated />
using System;
using ELKH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELKH.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525162956_RemoveContactDetailUserId")]
    partial class RemoveContactDetailUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ELKH.Models.AuditEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AffectedKeysCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("ELKH.Models.CachedFuzzyKeyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedFuzzyKeys", (string)null);
                });

            modelBuilder.Entity("ELKH.Models.CartModel", b =>
                {
                    b.Property<int>("PkCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductPkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegisteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("PkCartId");

                    b.HasIndex("ProductPkProductId");

                    b.HasIndex("RegisteredUserPkRegisteredUserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ELKH.Models.CategoryModel", b =>
                {
                    b.Property<int>("PkCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PkCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ELKH.Models.ContactDetailModel", b =>
                {
                    b.Property<int>("PkContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegisteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PkContactId");

                    b.HasIndex("RegisteredUserPkRegisteredUserId");

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("ELKH.Models.CouponModel", b =>
                {
                    b.Property<int>("PkCouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinimumOrderValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("PkCouponId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Coupons_Code_Unique");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("ELKH.Models.FuzzySuggestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized")
                        .HasDatabaseName("IX_FuzzySuggestions_NameNormalized");

                    b.HasIndex("PkProductId");

                    b.ToTable("FuzzySuggestions", (string)null);
                });

            modelBuilder.Entity("ELKH.Models.MessageReplyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RepliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepliedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageReplies");
                });

            modelBuilder.Entity("ELKH.Models.OrderCouponModel", b =>
                {
                    b.Property<int>("PkOrderCouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CouponCodeUsed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FkCouponId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkOrderCouponId");

                    b.HasIndex("FkCouponId");

                    b.HasIndex("FkOrderId");

                    b.ToTable("OrderCoupons");
                });

            modelBuilder.Entity("ELKH.Models.OrderItemModel", b =>
                {
                    b.Property<int>("PkOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderPkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductModelPkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("PkOrderItemId");

                    b.HasIndex("FkProductId");

                    b.HasIndex("OrderPkOrderId");

                    b.HasIndex("ProductModelPkProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ELKH.Models.OrderModel", b =>
                {
                    b.Property<int>("PkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactDetailPkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CouponDiscount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryStatus")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkShippingMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestAccessTokenHash")
                        .HasMaxLength(88)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingMethodName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShippingMethodPkShippingMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("PkOrderId");

                    b.HasIndex("ContactDetailPkContactId");

                    b.HasIndex("FkRegisteredUserId");

                    b.HasIndex("GuestAccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_GuestAccessTokenHash");

                    b.HasIndex("ShippingMethodPkShippingMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ELKH.Models.ProductImageModel", b =>
                {
                    b.Property<int>("PkProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductPkProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkProductImageId");

                    b.HasIndex("ProductPkProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("ELKH.Models.ProductModel", b =>
                {
                    b.Property<int>("PkProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryPkCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastNotificationSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockQuantity")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("PkProductId");

                    b.HasIndex("CategoryPkCategoryId");

                    b.HasIndex("NameNormalized")
                        .HasDatabaseName("IX_Products_NameNormalized");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ELKH.Models.ProductRatingModel", b =>
                {
                    b.Property<int>("PkRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FkOrderItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeratorNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductsPkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegisteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PkRatingId");

                    b.HasIndex("ProductsPkProductId");

                    b.HasIndex("RegisteredUserPkRegisteredUserId");

                    b.ToTable("ProductRatings");
                });

            modelBuilder.Entity("ELKH.Models.RegisteredUserModel", b =>
                {
                    b.Property<int>("PkRegisteredUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("PkRegisteredUserId");

                    b.ToTable("RegisteredUsers");
                });

            modelBuilder.Entity("ELKH.Models.ShippingMethodModel", b =>
                {
                    b.Property<int>("PkShippingMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryDaysMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryDaysMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PkShippingMethodId");

                    b.ToTable("ShippingMethods");
                });

            modelBuilder.Entity("ELKH.Models.StaffMessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StaffMessages");
                });

            modelBuilder.Entity("ELKH.Models.StockNotificationModel", b =>
                {
                    b.Property<int>("PkStockNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductPkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegisteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PkStockNotificationId");

                    b.HasIndex("ProductPkProductId");

                    b.HasIndex("RegisteredUserPkRegisteredUserId");

                    b.ToTable("StockNotifications");
                });

            modelBuilder.Entity("ELKH.Models.StoreReviewModel", b =>
                {
                    b.Property<int>("PkStoreReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerifiedBuyer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeratorNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegisteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PkStoreReviewId");

                    b.HasIndex("RegisteredUserPkRegisteredUserId");

                    b.ToTable("StoreReviews");
                });

            modelBuilder.Entity("ELKH.Models.TransactionModel", b =>
                {
                    b.Property<int>("PkTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContactDetailPkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentCapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PkTransactionId");

                    b.HasIndex("ContactDetailPkContactId");

                    b.HasIndex("FkOrderId")
                        .IsUnique();

                    b.HasIndex("PaymentOrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Transactions_PaymentOrderId_Unique");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Transactions_PaymentTransactionId_Unique");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ELKH.Models.UserLogModel", b =>
                {
                    b.Property<int>("PkLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Abandoned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityDetail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FkEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogOutTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkLogId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("ELKH.Models.UserProfileModel", b =>
                {
                    b.Property<string>("PkEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AvatarData")
                        .HasColumnType("BLOB");

                    b.Property<string>("AvatarMimeType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PkEmail");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ELKH.Models.WishListItemModel", b =>
                {
                    b.Property<int>("PkWishListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkWishListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkWishListItemId");

                    b.HasIndex("FkProductId");

                    b.HasIndex("FkWishListId");

                    b.ToTable("WishListItems");
                });

            modelBuilder.Entity("ELKH.Models.WishListModel", b =>
                {
                    b.Property<int>("PkWishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkWishListId");

                    b.HasIndex("FkUserId")
                        .IsUnique();

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ELKH.Models.CartModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductPkProductId");

                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany("Cart")
                        .HasForeignKey("RegisteredUserPkRegisteredUserId");

                    b.Navigation("Product");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ELKH.Models.ContactDetailModel", b =>
                {
                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany("ContactDetails")
                        .HasForeignKey("RegisteredUserPkRegisteredUserId");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ELKH.Models.FuzzySuggestionModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", null)
                        .WithMany("FuzzySuggestions")
                        .HasForeignKey("PkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ELKH.Models.MessageReplyModel", b =>
                {
                    b.HasOne("ELKH.Models.StaffMessageModel", "Message")
                        .WithMany("Replies")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("ELKH.Models.OrderCouponModel", b =>
                {
                    b.HasOne("ELKH.Models.CouponModel", "Coupon")
                        .WithMany("OrderCoupons")
                        .HasForeignKey("FkCouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ELKH.Models.OrderModel", "Order")
                        .WithMany("OrderCoupons")
                        .HasForeignKey("FkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ELKH.Models.OrderItemModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("FkProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ELKH.Models.OrderModel", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderPkOrderId");

                    b.HasOne("ELKH.Models.ProductModel", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductModelPkProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ELKH.Models.OrderModel", b =>
                {
                    b.HasOne("ELKH.Models.ContactDetailModel", "ContactDetail")
                        .WithMany("Orders")
                        .HasForeignKey("ContactDetailPkContactId");

                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany("Orders")
                        .HasForeignKey("FkRegisteredUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ELKH.Models.ShippingMethodModel", "ShippingMethod")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingMethodPkShippingMethodId");

                    b.Navigation("ContactDetail");

                    b.Navigation("RegisteredUser");

                    b.Navigation("ShippingMethod");
                });

            modelBuilder.Entity("ELKH.Models.ProductImageModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Product")
                        .WithMany("ProductImage")
                        .HasForeignKey("ProductPkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ELKH.Models.ProductModel", b =>
                {
                    b.HasOne("ELKH.Models.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryPkCategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ELKH.Models.ProductRatingModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Products")
                        .WithMany("ProductRatings")
                        .HasForeignKey("ProductsPkProductId");

                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany("ProductRatings")
                        .HasForeignKey("RegisteredUserPkRegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ELKH.Models.StockNotificationModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductPkProductId");

                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany()
                        .HasForeignKey("RegisteredUserPkRegisteredUserId");

                    b.Navigation("Product");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ELKH.Models.StoreReviewModel", b =>
                {
                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany("StoreReviews")
                        .HasForeignKey("RegisteredUserPkRegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ELKH.Models.TransactionModel", b =>
                {
                    b.HasOne("ELKH.Models.ContactDetailModel", "ContactDetail")
                        .WithMany("Transactions")
                        .HasForeignKey("ContactDetailPkContactId");

                    b.HasOne("ELKH.Models.OrderModel", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("ELKH.Models.TransactionModel", "FkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ELKH.Models.UserLogModel", b =>
                {
                    b.HasOne("ELKH.Models.RegisteredUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ELKH.Models.WishListItemModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Product")
                        .WithMany("WishListItems")
                        .HasForeignKey("FkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELKH.Models.WishListModel", "WishList")
                        .WithMany("WishListItems")
                        .HasForeignKey("FkWishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("ELKH.Models.WishListModel", b =>
                {
                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithOne("WishLists")
                        .HasForeignKey("ELKH.Models.WishListModel", "FkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ELKH.Models.CategoryModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ELKH.Models.ContactDetailModel", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ELKH.Models.CouponModel", b =>
                {
                    b.Navigation("OrderCoupons");
                });

            modelBuilder.Entity("ELKH.Models.OrderModel", b =>
                {
                    b.Navigation("OrderCoupons");

                    b.Navigation("OrderItems");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ELKH.Models.ProductModel", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("FuzzySuggestions");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImage");

                    b.Navigation("ProductRatings");

                    b.Navigation("WishListItems");
                });

            modelBuilder.Entity("ELKH.Models.RegisteredUserModel", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("ContactDetails");

                    b.Navigation("Orders");

                    b.Navigation("ProductRatings");

                    b.Navigation("StoreReviews");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("ELKH.Models.ShippingMethodModel", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ELKH.Models.StaffMessageModel", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ELKH.Models.WishListModel", b =>
                {
                    b.Navigation("WishListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
